# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: 'bin/{{ .ProjectName }}'
  goos:
    - linux
    - darwin
    - windows
    - freebsd
  goarch:
    - amd64
    - '386'
    - arm64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_sha256-checksums.txt'

archives:
  - format: tar.gz
    id: release-archive
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

nfpms:
  -
    vendor: Sensu, Inc.
    # Your app's homepage.
    # Default is empty.
    homepage: https://sensu.io

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Eric Chlebek <eric@sensu.io>

    # Your app's description.
    # Default is empty.
    description: High performance log file analyzer.

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Packages your package depends on.
    dependencies: []

    # Packages your package recommends installing.
    # For RPM packages rpmbuild >= 4.13 is required
    recommends: []

    # Packages your package suggests installing.
    # For RPM packages rpmbuild >= 4.13 is required
    suggests: []

    # Packages that conflict with your package.
    conflicts: []

    # Override default /usr/local/bin destination for binaries
    # bindir: /usr/bin

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.
    empty_folders:
    - /etc/sensu-check-log
